name: CollegeBot

on:
  schedule:
    - cron: '0 2 * * 0-5' # run the job every weekday at 8am Nepal time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run bot
      run: timeout 1h python CollegeBot.py
